# Generated by Django 5.1.1 on 2025-03-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaggedmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='flaggedmessage',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='flaggedmessage',
            name='chat_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='flaggedmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='flaggedmessage',
            name='user_id',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
